# HTTP Server
[server]
	Address     = ":8199"
	ServerRoot  = "public"
	ServerAgent = "gf-app"
	LogPath     = "/tmp/log/gfim/server"

# Logger.
[logger]
    Path        = "/tmp/log/gfim"
    Level       = "all"
    Stdout      = true

# Template.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  =  ["${", "}"]

# Database.
[database]
    link  = "mysql:root:123456@tcp(127.0.0.1:3306)/gfim"
    debug = true
    # Database logger.
    [database.logger]
        Path   = "/tmp/log/gfim/sql"
        Level  = "all"
        Stdout = true
# Redis数据库配置
[redis]
    default = "127.0.0.1:6379,0"

[websocket]
    Address = "ws://127.0.0.1:8199/chat"